/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppShellRouteRouteImport } from './routes/_app/_shell/route'
import { Route as AppOnboardRouteImport } from './routes/_app/onboard'
import { Route as AppShellAuthenticationRouteRouteImport } from './routes/_app/_shell/authentication/route'
import { Route as AppShellDashboardRouteImport } from './routes/_app/_shell/dashboard'
import { Route as AppShellFeaturesRouteRouteImport } from './routes/_app/_shell/features/route'
import { Route as AppShellLoginFlowsRouteImport } from './routes/_app/_shell/login-flows'
import { Route as AppShellSettingsRouteRouteImport } from './routes/_app/_shell/settings/route'
import { Route as AppShellTestAccountsRouteImport } from './routes/_app/_shell/test-accounts'
import { Route as AppShellTestRunsRouteImport } from './routes/_app/_shell/test-runs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'
import { Route as AppShellAuthenticationIndexRouteImport } from './routes/_app/_shell/authentication/index'
import { Route as AppShellAuthenticationAccountsRouteImport } from './routes/_app/_shell/authentication/accounts'
import { Route as AppShellAuthenticationLoginFlowRouteImport } from './routes/_app/_shell/authentication/login-flow'
import { Route as AppShellFeaturesIndexRouteImport } from './routes/_app/_shell/features/index'
import { Route as AppShellFeaturesFeatureIdRouteImport } from './routes/_app/_shell/features/$featureId'
import { Route as AppShellSettingsIndexRouteImport } from './routes/_app/_shell/settings/index'
import { Route as AppShellSettingsApiKeysRouteImport } from './routes/_app/_shell/settings/api-keys'
import { Route as AppShellSettingsProjectRouteImport } from './routes/_app/_shell/settings/project'
import { Route as ApiV1TestRunsTestRunIdRouteImport } from './routes/api/v1/test-runs/$testRunId'
import { Route as ApiScreenshotsTestRunsTestRunIdStepIdRouteImport } from './routes/api/screenshots/test-runs/$testRunId/$stepId'
import { Route as ApiV1FeaturesFeatureIdTestCasesRouteImport } from './routes/api/v1/features/$featureId/test-cases'
import { Route as ApiV1ProjectsProjectIdFeaturesRouteImport } from './routes/api/v1/projects/$projectId/features'
import { Route as ApiV1ProjectsProjectIdTestRunsRouteImport } from './routes/api/v1/projects/$projectId/test-runs'
import { Route as ApiV1TestCasesTestCaseIdRunRouteImport } from './routes/api/v1/test-cases/$testCaseId/run'
import { Route as ApiV1TestCasesTestCaseIdStepsRouteImport } from './routes/api/v1/test-cases/$testCaseId/steps'
import { Route as ApiV1TestRunsTestRunIdCancelRouteImport } from './routes/api/v1/test-runs/$testRunId.cancel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRouteRoute = AppShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShellAuthenticationRouteRoute =
  AppShellAuthenticationRouteRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AppShellRouteRoute,
  } as any)
const AppShellDashboardRoute = AppShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellFeaturesRouteRoute = AppShellFeaturesRouteRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellLoginFlowsRoute = AppShellLoginFlowsRouteImport.update({
  id: '/login-flows',
  path: '/login-flows',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellSettingsRouteRoute = AppShellSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellTestAccountsRoute = AppShellTestAccountsRouteImport.update({
  id: '/test-accounts',
  path: '/test-accounts',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellTestRunsRoute = AppShellTestRunsRouteImport.update({
  id: '/test-runs',
  path: '/test-runs',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellAuthenticationIndexRoute =
  AppShellAuthenticationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppShellAuthenticationRouteRoute,
  } as any)
const AppShellAuthenticationAccountsRoute =
  AppShellAuthenticationAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AppShellAuthenticationRouteRoute,
  } as any)
const AppShellAuthenticationLoginFlowRoute =
  AppShellAuthenticationLoginFlowRouteImport.update({
    id: '/login-flow',
    path: '/login-flow',
    getParentRoute: () => AppShellAuthenticationRouteRoute,
  } as any)
const AppShellFeaturesIndexRoute = AppShellFeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellFeaturesRouteRoute,
} as any)
const AppShellFeaturesFeatureIdRoute =
  AppShellFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => AppShellFeaturesRouteRoute,
  } as any)
const AppShellSettingsIndexRoute = AppShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellSettingsRouteRoute,
} as any)
const AppShellSettingsApiKeysRoute = AppShellSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppShellSettingsRouteRoute,
} as any)
const AppShellSettingsProjectRoute = AppShellSettingsProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AppShellSettingsRouteRoute,
} as any)
const ApiV1TestRunsTestRunIdRoute = ApiV1TestRunsTestRunIdRouteImport.update({
  id: '/api/v1/test-runs/$testRunId',
  path: '/api/v1/test-runs/$testRunId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotsTestRunsTestRunIdStepIdRoute =
  ApiScreenshotsTestRunsTestRunIdStepIdRouteImport.update({
    id: '/api/screenshots/test-runs/$testRunId/$stepId',
    path: '/api/screenshots/test-runs/$testRunId/$stepId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FeaturesFeatureIdTestCasesRoute =
  ApiV1FeaturesFeatureIdTestCasesRouteImport.update({
    id: '/api/v1/features/$featureId/test-cases',
    path: '/api/v1/features/$featureId/test-cases',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectIdFeaturesRoute =
  ApiV1ProjectsProjectIdFeaturesRouteImport.update({
    id: '/$projectId/features',
    path: '/$projectId/features',
    getParentRoute: () => ApiV1ProjectsRoute,
  } as any)
const ApiV1ProjectsProjectIdTestRunsRoute =
  ApiV1ProjectsProjectIdTestRunsRouteImport.update({
    id: '/$projectId/test-runs',
    path: '/$projectId/test-runs',
    getParentRoute: () => ApiV1ProjectsRoute,
  } as any)
const ApiV1TestCasesTestCaseIdRunRoute =
  ApiV1TestCasesTestCaseIdRunRouteImport.update({
    id: '/api/v1/test-cases/$testCaseId/run',
    path: '/api/v1/test-cases/$testCaseId/run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1TestCasesTestCaseIdStepsRoute =
  ApiV1TestCasesTestCaseIdStepsRouteImport.update({
    id: '/api/v1/test-cases/$testCaseId/steps',
    path: '/api/v1/test-cases/$testCaseId/steps',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1TestRunsTestRunIdCancelRoute =
  ApiV1TestRunsTestRunIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiV1TestRunsTestRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboard': typeof AppOnboardRoute
  '/authentication': typeof AppShellAuthenticationRouteRouteWithChildren
  '/features': typeof AppShellFeaturesRouteRouteWithChildren
  '/settings': typeof AppShellSettingsRouteRouteWithChildren
  '/dashboard': typeof AppShellDashboardRoute
  '/login-flows': typeof AppShellLoginFlowsRoute
  '/test-accounts': typeof AppShellTestAccountsRoute
  '/test-runs': typeof AppShellTestRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/authentication/accounts': typeof AppShellAuthenticationAccountsRoute
  '/authentication/login-flow': typeof AppShellAuthenticationLoginFlowRoute
  '/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/settings/api-keys': typeof AppShellSettingsApiKeysRoute
  '/settings/project': typeof AppShellSettingsProjectRoute
  '/api/v1/test-runs/$testRunId': typeof ApiV1TestRunsTestRunIdRouteWithChildren
  '/authentication/': typeof AppShellAuthenticationIndexRoute
  '/features/': typeof AppShellFeaturesIndexRoute
  '/settings/': typeof AppShellSettingsIndexRoute
  '/api/screenshots/test-runs/$testRunId/$stepId': typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
  '/api/v1/features/$featureId/test-cases': typeof ApiV1FeaturesFeatureIdTestCasesRoute
  '/api/v1/projects/$projectId/features': typeof ApiV1ProjectsProjectIdFeaturesRoute
  '/api/v1/projects/$projectId/test-runs': typeof ApiV1ProjectsProjectIdTestRunsRoute
  '/api/v1/test-cases/$testCaseId/run': typeof ApiV1TestCasesTestCaseIdRunRoute
  '/api/v1/test-cases/$testCaseId/steps': typeof ApiV1TestCasesTestCaseIdStepsRoute
  '/api/v1/test-runs/$testRunId/cancel': typeof ApiV1TestRunsTestRunIdCancelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboard': typeof AppOnboardRoute
  '/dashboard': typeof AppShellDashboardRoute
  '/login-flows': typeof AppShellLoginFlowsRoute
  '/test-accounts': typeof AppShellTestAccountsRoute
  '/test-runs': typeof AppShellTestRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/authentication/accounts': typeof AppShellAuthenticationAccountsRoute
  '/authentication/login-flow': typeof AppShellAuthenticationLoginFlowRoute
  '/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/settings/api-keys': typeof AppShellSettingsApiKeysRoute
  '/settings/project': typeof AppShellSettingsProjectRoute
  '/api/v1/test-runs/$testRunId': typeof ApiV1TestRunsTestRunIdRouteWithChildren
  '/authentication': typeof AppShellAuthenticationIndexRoute
  '/features': typeof AppShellFeaturesIndexRoute
  '/settings': typeof AppShellSettingsIndexRoute
  '/api/screenshots/test-runs/$testRunId/$stepId': typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
  '/api/v1/features/$featureId/test-cases': typeof ApiV1FeaturesFeatureIdTestCasesRoute
  '/api/v1/projects/$projectId/features': typeof ApiV1ProjectsProjectIdFeaturesRoute
  '/api/v1/projects/$projectId/test-runs': typeof ApiV1ProjectsProjectIdTestRunsRoute
  '/api/v1/test-cases/$testCaseId/run': typeof ApiV1TestCasesTestCaseIdRunRoute
  '/api/v1/test-cases/$testCaseId/steps': typeof ApiV1TestCasesTestCaseIdStepsRoute
  '/api/v1/test-runs/$testRunId/cancel': typeof ApiV1TestRunsTestRunIdCancelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/_shell': typeof AppShellRouteRouteWithChildren
  '/_app/onboard': typeof AppOnboardRoute
  '/_app/_shell/authentication': typeof AppShellAuthenticationRouteRouteWithChildren
  '/_app/_shell/features': typeof AppShellFeaturesRouteRouteWithChildren
  '/_app/_shell/settings': typeof AppShellSettingsRouteRouteWithChildren
  '/_app/_shell/dashboard': typeof AppShellDashboardRoute
  '/_app/_shell/login-flows': typeof AppShellLoginFlowsRoute
  '/_app/_shell/test-accounts': typeof AppShellTestAccountsRoute
  '/_app/_shell/test-runs': typeof AppShellTestRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/_app/_shell/authentication/accounts': typeof AppShellAuthenticationAccountsRoute
  '/_app/_shell/authentication/login-flow': typeof AppShellAuthenticationLoginFlowRoute
  '/_app/_shell/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/_app/_shell/settings/api-keys': typeof AppShellSettingsApiKeysRoute
  '/_app/_shell/settings/project': typeof AppShellSettingsProjectRoute
  '/api/v1/test-runs/$testRunId': typeof ApiV1TestRunsTestRunIdRouteWithChildren
  '/_app/_shell/authentication/': typeof AppShellAuthenticationIndexRoute
  '/_app/_shell/features/': typeof AppShellFeaturesIndexRoute
  '/_app/_shell/settings/': typeof AppShellSettingsIndexRoute
  '/api/screenshots/test-runs/$testRunId/$stepId': typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
  '/api/v1/features/$featureId/test-cases': typeof ApiV1FeaturesFeatureIdTestCasesRoute
  '/api/v1/projects/$projectId/features': typeof ApiV1ProjectsProjectIdFeaturesRoute
  '/api/v1/projects/$projectId/test-runs': typeof ApiV1ProjectsProjectIdTestRunsRoute
  '/api/v1/test-cases/$testCaseId/run': typeof ApiV1TestCasesTestCaseIdRunRoute
  '/api/v1/test-cases/$testCaseId/steps': typeof ApiV1TestCasesTestCaseIdStepsRoute
  '/api/v1/test-runs/$testRunId/cancel': typeof ApiV1TestRunsTestRunIdCancelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/onboard'
    | '/authentication'
    | '/features'
    | '/settings'
    | '/dashboard'
    | '/login-flows'
    | '/test-accounts'
    | '/test-runs'
    | '/api/auth/$'
    | '/api/v1/projects'
    | '/authentication/accounts'
    | '/authentication/login-flow'
    | '/features/$featureId'
    | '/settings/api-keys'
    | '/settings/project'
    | '/api/v1/test-runs/$testRunId'
    | '/authentication/'
    | '/features/'
    | '/settings/'
    | '/api/screenshots/test-runs/$testRunId/$stepId'
    | '/api/v1/features/$featureId/test-cases'
    | '/api/v1/projects/$projectId/features'
    | '/api/v1/projects/$projectId/test-runs'
    | '/api/v1/test-cases/$testCaseId/run'
    | '/api/v1/test-cases/$testCaseId/steps'
    | '/api/v1/test-runs/$testRunId/cancel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/onboard'
    | '/dashboard'
    | '/login-flows'
    | '/test-accounts'
    | '/test-runs'
    | '/api/auth/$'
    | '/api/v1/projects'
    | '/authentication/accounts'
    | '/authentication/login-flow'
    | '/features/$featureId'
    | '/settings/api-keys'
    | '/settings/project'
    | '/api/v1/test-runs/$testRunId'
    | '/authentication'
    | '/features'
    | '/settings'
    | '/api/screenshots/test-runs/$testRunId/$stepId'
    | '/api/v1/features/$featureId/test-cases'
    | '/api/v1/projects/$projectId/features'
    | '/api/v1/projects/$projectId/test-runs'
    | '/api/v1/test-cases/$testCaseId/run'
    | '/api/v1/test-cases/$testCaseId/steps'
    | '/api/v1/test-runs/$testRunId/cancel'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/_shell'
    | '/_app/onboard'
    | '/_app/_shell/authentication'
    | '/_app/_shell/features'
    | '/_app/_shell/settings'
    | '/_app/_shell/dashboard'
    | '/_app/_shell/login-flows'
    | '/_app/_shell/test-accounts'
    | '/_app/_shell/test-runs'
    | '/api/auth/$'
    | '/api/v1/projects'
    | '/_app/_shell/authentication/accounts'
    | '/_app/_shell/authentication/login-flow'
    | '/_app/_shell/features/$featureId'
    | '/_app/_shell/settings/api-keys'
    | '/_app/_shell/settings/project'
    | '/api/v1/test-runs/$testRunId'
    | '/_app/_shell/authentication/'
    | '/_app/_shell/features/'
    | '/_app/_shell/settings/'
    | '/api/screenshots/test-runs/$testRunId/$stepId'
    | '/api/v1/features/$featureId/test-cases'
    | '/api/v1/projects/$projectId/features'
    | '/api/v1/projects/$projectId/test-runs'
    | '/api/v1/test-cases/$testCaseId/run'
    | '/api/v1/test-cases/$testCaseId/steps'
    | '/api/v1/test-runs/$testRunId/cancel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRouteWithChildren
  ApiV1TestRunsTestRunIdRoute: typeof ApiV1TestRunsTestRunIdRouteWithChildren
  ApiScreenshotsTestRunsTestRunIdStepIdRoute: typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
  ApiV1FeaturesFeatureIdTestCasesRoute: typeof ApiV1FeaturesFeatureIdTestCasesRoute
  ApiV1TestCasesTestCaseIdRunRoute: typeof ApiV1TestCasesTestCaseIdRunRoute
  ApiV1TestCasesTestCaseIdStepsRoute: typeof ApiV1TestCasesTestCaseIdStepsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboard': {
      id: '/_app/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_shell/authentication': {
      id: '/_app/_shell/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AppShellAuthenticationRouteRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/dashboard': {
      id: '/_app/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppShellDashboardRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/features': {
      id: '/_app/_shell/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AppShellFeaturesRouteRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/login-flows': {
      id: '/_app/_shell/login-flows'
      path: '/login-flows'
      fullPath: '/login-flows'
      preLoaderRoute: typeof AppShellLoginFlowsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/settings': {
      id: '/_app/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppShellSettingsRouteRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/test-accounts': {
      id: '/_app/_shell/test-accounts'
      path: '/test-accounts'
      fullPath: '/test-accounts'
      preLoaderRoute: typeof AppShellTestAccountsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/test-runs': {
      id: '/_app/_shell/test-runs'
      path: '/test-runs'
      fullPath: '/test-runs'
      preLoaderRoute: typeof AppShellTestRunsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/authentication/': {
      id: '/_app/_shell/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AppShellAuthenticationIndexRouteImport
      parentRoute: typeof AppShellAuthenticationRouteRoute
    }
    '/_app/_shell/authentication/accounts': {
      id: '/_app/_shell/authentication/accounts'
      path: '/accounts'
      fullPath: '/authentication/accounts'
      preLoaderRoute: typeof AppShellAuthenticationAccountsRouteImport
      parentRoute: typeof AppShellAuthenticationRouteRoute
    }
    '/_app/_shell/authentication/login-flow': {
      id: '/_app/_shell/authentication/login-flow'
      path: '/login-flow'
      fullPath: '/authentication/login-flow'
      preLoaderRoute: typeof AppShellAuthenticationLoginFlowRouteImport
      parentRoute: typeof AppShellAuthenticationRouteRoute
    }
    '/_app/_shell/features/': {
      id: '/_app/_shell/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof AppShellFeaturesIndexRouteImport
      parentRoute: typeof AppShellFeaturesRouteRoute
    }
    '/_app/_shell/features/$featureId': {
      id: '/_app/_shell/features/$featureId'
      path: '/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof AppShellFeaturesFeatureIdRouteImport
      parentRoute: typeof AppShellFeaturesRouteRoute
    }
    '/_app/_shell/settings/': {
      id: '/_app/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppShellSettingsIndexRouteImport
      parentRoute: typeof AppShellSettingsRouteRoute
    }
    '/_app/_shell/settings/api-keys': {
      id: '/_app/_shell/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppShellSettingsApiKeysRouteImport
      parentRoute: typeof AppShellSettingsRouteRoute
    }
    '/_app/_shell/settings/project': {
      id: '/_app/_shell/settings/project'
      path: '/project'
      fullPath: '/settings/project'
      preLoaderRoute: typeof AppShellSettingsProjectRouteImport
      parentRoute: typeof AppShellSettingsRouteRoute
    }
    '/api/v1/test-runs/$testRunId': {
      id: '/api/v1/test-runs/$testRunId'
      path: '/api/v1/test-runs/$testRunId'
      fullPath: '/api/v1/test-runs/$testRunId'
      preLoaderRoute: typeof ApiV1TestRunsTestRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshots/test-runs/$testRunId/$stepId': {
      id: '/api/screenshots/test-runs/$testRunId/$stepId'
      path: '/api/screenshots/test-runs/$testRunId/$stepId'
      fullPath: '/api/screenshots/test-runs/$testRunId/$stepId'
      preLoaderRoute: typeof ApiScreenshotsTestRunsTestRunIdStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/features/$featureId/test-cases': {
      id: '/api/v1/features/$featureId/test-cases'
      path: '/api/v1/features/$featureId/test-cases'
      fullPath: '/api/v1/features/$featureId/test-cases'
      preLoaderRoute: typeof ApiV1FeaturesFeatureIdTestCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId/features': {
      id: '/api/v1/projects/$projectId/features'
      path: '/$projectId/features'
      fullPath: '/api/v1/projects/$projectId/features'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdFeaturesRouteImport
      parentRoute: typeof ApiV1ProjectsRoute
    }
    '/api/v1/projects/$projectId/test-runs': {
      id: '/api/v1/projects/$projectId/test-runs'
      path: '/$projectId/test-runs'
      fullPath: '/api/v1/projects/$projectId/test-runs'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTestRunsRouteImport
      parentRoute: typeof ApiV1ProjectsRoute
    }
    '/api/v1/test-cases/$testCaseId/run': {
      id: '/api/v1/test-cases/$testCaseId/run'
      path: '/api/v1/test-cases/$testCaseId/run'
      fullPath: '/api/v1/test-cases/$testCaseId/run'
      preLoaderRoute: typeof ApiV1TestCasesTestCaseIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/test-cases/$testCaseId/steps': {
      id: '/api/v1/test-cases/$testCaseId/steps'
      path: '/api/v1/test-cases/$testCaseId/steps'
      fullPath: '/api/v1/test-cases/$testCaseId/steps'
      preLoaderRoute: typeof ApiV1TestCasesTestCaseIdStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/test-runs/$testRunId/cancel': {
      id: '/api/v1/test-runs/$testRunId/cancel'
      path: '/cancel'
      fullPath: '/api/v1/test-runs/$testRunId/cancel'
      preLoaderRoute: typeof ApiV1TestRunsTestRunIdCancelRouteImport
      parentRoute: typeof ApiV1TestRunsTestRunIdRoute
    }
  }
}

interface AppShellAuthenticationRouteRouteChildren {
  AppShellAuthenticationAccountsRoute: typeof AppShellAuthenticationAccountsRoute
  AppShellAuthenticationLoginFlowRoute: typeof AppShellAuthenticationLoginFlowRoute
  AppShellAuthenticationIndexRoute: typeof AppShellAuthenticationIndexRoute
}

const AppShellAuthenticationRouteRouteChildren: AppShellAuthenticationRouteRouteChildren =
  {
    AppShellAuthenticationAccountsRoute: AppShellAuthenticationAccountsRoute,
    AppShellAuthenticationLoginFlowRoute: AppShellAuthenticationLoginFlowRoute,
    AppShellAuthenticationIndexRoute: AppShellAuthenticationIndexRoute,
  }

const AppShellAuthenticationRouteRouteWithChildren =
  AppShellAuthenticationRouteRoute._addFileChildren(
    AppShellAuthenticationRouteRouteChildren,
  )

interface AppShellFeaturesRouteRouteChildren {
  AppShellFeaturesFeatureIdRoute: typeof AppShellFeaturesFeatureIdRoute
  AppShellFeaturesIndexRoute: typeof AppShellFeaturesIndexRoute
}

const AppShellFeaturesRouteRouteChildren: AppShellFeaturesRouteRouteChildren = {
  AppShellFeaturesFeatureIdRoute: AppShellFeaturesFeatureIdRoute,
  AppShellFeaturesIndexRoute: AppShellFeaturesIndexRoute,
}

const AppShellFeaturesRouteRouteWithChildren =
  AppShellFeaturesRouteRoute._addFileChildren(
    AppShellFeaturesRouteRouteChildren,
  )

interface AppShellSettingsRouteRouteChildren {
  AppShellSettingsApiKeysRoute: typeof AppShellSettingsApiKeysRoute
  AppShellSettingsProjectRoute: typeof AppShellSettingsProjectRoute
  AppShellSettingsIndexRoute: typeof AppShellSettingsIndexRoute
}

const AppShellSettingsRouteRouteChildren: AppShellSettingsRouteRouteChildren = {
  AppShellSettingsApiKeysRoute: AppShellSettingsApiKeysRoute,
  AppShellSettingsProjectRoute: AppShellSettingsProjectRoute,
  AppShellSettingsIndexRoute: AppShellSettingsIndexRoute,
}

const AppShellSettingsRouteRouteWithChildren =
  AppShellSettingsRouteRoute._addFileChildren(
    AppShellSettingsRouteRouteChildren,
  )

interface AppShellRouteRouteChildren {
  AppShellAuthenticationRouteRoute: typeof AppShellAuthenticationRouteRouteWithChildren
  AppShellFeaturesRouteRoute: typeof AppShellFeaturesRouteRouteWithChildren
  AppShellSettingsRouteRoute: typeof AppShellSettingsRouteRouteWithChildren
  AppShellDashboardRoute: typeof AppShellDashboardRoute
  AppShellLoginFlowsRoute: typeof AppShellLoginFlowsRoute
  AppShellTestAccountsRoute: typeof AppShellTestAccountsRoute
  AppShellTestRunsRoute: typeof AppShellTestRunsRoute
}

const AppShellRouteRouteChildren: AppShellRouteRouteChildren = {
  AppShellAuthenticationRouteRoute:
    AppShellAuthenticationRouteRouteWithChildren,
  AppShellFeaturesRouteRoute: AppShellFeaturesRouteRouteWithChildren,
  AppShellSettingsRouteRoute: AppShellSettingsRouteRouteWithChildren,
  AppShellDashboardRoute: AppShellDashboardRoute,
  AppShellLoginFlowsRoute: AppShellLoginFlowsRoute,
  AppShellTestAccountsRoute: AppShellTestAccountsRoute,
  AppShellTestRunsRoute: AppShellTestRunsRoute,
}

const AppShellRouteRouteWithChildren = AppShellRouteRoute._addFileChildren(
  AppShellRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppShellRouteRoute: typeof AppShellRouteRouteWithChildren
  AppOnboardRoute: typeof AppOnboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppShellRouteRoute: AppShellRouteRouteWithChildren,
  AppOnboardRoute: AppOnboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiV1ProjectsRouteChildren {
  ApiV1ProjectsProjectIdFeaturesRoute: typeof ApiV1ProjectsProjectIdFeaturesRoute
  ApiV1ProjectsProjectIdTestRunsRoute: typeof ApiV1ProjectsProjectIdTestRunsRoute
}

const ApiV1ProjectsRouteChildren: ApiV1ProjectsRouteChildren = {
  ApiV1ProjectsProjectIdFeaturesRoute: ApiV1ProjectsProjectIdFeaturesRoute,
  ApiV1ProjectsProjectIdTestRunsRoute: ApiV1ProjectsProjectIdTestRunsRoute,
}

const ApiV1ProjectsRouteWithChildren = ApiV1ProjectsRoute._addFileChildren(
  ApiV1ProjectsRouteChildren,
)

interface ApiV1TestRunsTestRunIdRouteChildren {
  ApiV1TestRunsTestRunIdCancelRoute: typeof ApiV1TestRunsTestRunIdCancelRoute
}

const ApiV1TestRunsTestRunIdRouteChildren: ApiV1TestRunsTestRunIdRouteChildren =
  {
    ApiV1TestRunsTestRunIdCancelRoute: ApiV1TestRunsTestRunIdCancelRoute,
  }

const ApiV1TestRunsTestRunIdRouteWithChildren =
  ApiV1TestRunsTestRunIdRoute._addFileChildren(
    ApiV1TestRunsTestRunIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ProjectsRoute: ApiV1ProjectsRouteWithChildren,
  ApiV1TestRunsTestRunIdRoute: ApiV1TestRunsTestRunIdRouteWithChildren,
  ApiScreenshotsTestRunsTestRunIdStepIdRoute:
    ApiScreenshotsTestRunsTestRunIdStepIdRoute,
  ApiV1FeaturesFeatureIdTestCasesRoute: ApiV1FeaturesFeatureIdTestCasesRoute,
  ApiV1TestCasesTestCaseIdRunRoute: ApiV1TestCasesTestCaseIdRunRoute,
  ApiV1TestCasesTestCaseIdStepsRoute: ApiV1TestCasesTestCaseIdStepsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
