/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppShellRouteRouteImport } from './routes/_app/_shell/route'
import { Route as AppOnboardRouteImport } from './routes/_app/onboard'
import { Route as AppShellDashboardRouteImport } from './routes/_app/_shell/dashboard'
import { Route as AppShellFeaturesRouteRouteImport } from './routes/_app/_shell/features/route'
import { Route as AppShellTestAccountsRouteImport } from './routes/_app/_shell/test-accounts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppShellFeaturesIndexRouteImport } from './routes/_app/_shell/features/index'
import { Route as AppShellFeaturesFeatureIdRouteImport } from './routes/_app/_shell/features/$featureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRouteRoute = AppShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShellDashboardRoute = AppShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellFeaturesRouteRoute = AppShellFeaturesRouteRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellTestAccountsRoute = AppShellTestAccountsRouteImport.update({
  id: '/test-accounts',
  path: '/test-accounts',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellFeaturesIndexRoute = AppShellFeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellFeaturesRouteRoute,
} as any)
const AppShellFeaturesFeatureIdRoute =
  AppShellFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => AppShellFeaturesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboard': typeof AppOnboardRoute
  '/features': typeof AppShellFeaturesRouteRouteWithChildren
  '/dashboard': typeof AppShellDashboardRoute
  '/test-accounts': typeof AppShellTestAccountsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/features/': typeof AppShellFeaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboard': typeof AppOnboardRoute
  '/dashboard': typeof AppShellDashboardRoute
  '/test-accounts': typeof AppShellTestAccountsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/features': typeof AppShellFeaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/_shell': typeof AppShellRouteRouteWithChildren
  '/_app/onboard': typeof AppOnboardRoute
  '/_app/_shell/features': typeof AppShellFeaturesRouteRouteWithChildren
  '/_app/_shell/dashboard': typeof AppShellDashboardRoute
  '/_app/_shell/test-accounts': typeof AppShellTestAccountsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/_shell/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/_app/_shell/features/': typeof AppShellFeaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/onboard'
    | '/features'
    | '/dashboard'
    | '/test-accounts'
    | '/api/auth/$'
    | '/features/$featureId'
    | '/features/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/onboard'
    | '/dashboard'
    | '/test-accounts'
    | '/api/auth/$'
    | '/features/$featureId'
    | '/features'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/_shell'
    | '/_app/onboard'
    | '/_app/_shell/features'
    | '/_app/_shell/dashboard'
    | '/_app/_shell/test-accounts'
    | '/api/auth/$'
    | '/_app/_shell/features/$featureId'
    | '/_app/_shell/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboard': {
      id: '/_app/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_shell/dashboard': {
      id: '/_app/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppShellDashboardRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/features': {
      id: '/_app/_shell/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AppShellFeaturesRouteRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/test-accounts': {
      id: '/_app/_shell/test-accounts'
      path: '/test-accounts'
      fullPath: '/test-accounts'
      preLoaderRoute: typeof AppShellTestAccountsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/features/': {
      id: '/_app/_shell/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof AppShellFeaturesIndexRouteImport
      parentRoute: typeof AppShellFeaturesRouteRoute
    }
    '/_app/_shell/features/$featureId': {
      id: '/_app/_shell/features/$featureId'
      path: '/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof AppShellFeaturesFeatureIdRouteImport
      parentRoute: typeof AppShellFeaturesRouteRoute
    }
  }
}

interface AppShellFeaturesRouteRouteChildren {
  AppShellFeaturesFeatureIdRoute: typeof AppShellFeaturesFeatureIdRoute
  AppShellFeaturesIndexRoute: typeof AppShellFeaturesIndexRoute
}

const AppShellFeaturesRouteRouteChildren: AppShellFeaturesRouteRouteChildren = {
  AppShellFeaturesFeatureIdRoute: AppShellFeaturesFeatureIdRoute,
  AppShellFeaturesIndexRoute: AppShellFeaturesIndexRoute,
}

const AppShellFeaturesRouteRouteWithChildren =
  AppShellFeaturesRouteRoute._addFileChildren(
    AppShellFeaturesRouteRouteChildren,
  )

interface AppShellRouteRouteChildren {
  AppShellFeaturesRouteRoute: typeof AppShellFeaturesRouteRouteWithChildren
  AppShellDashboardRoute: typeof AppShellDashboardRoute
  AppShellTestAccountsRoute: typeof AppShellTestAccountsRoute
}

const AppShellRouteRouteChildren: AppShellRouteRouteChildren = {
  AppShellFeaturesRouteRoute: AppShellFeaturesRouteRouteWithChildren,
  AppShellDashboardRoute: AppShellDashboardRoute,
  AppShellTestAccountsRoute: AppShellTestAccountsRoute,
}

const AppShellRouteRouteWithChildren = AppShellRouteRoute._addFileChildren(
  AppShellRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppShellRouteRoute: typeof AppShellRouteRouteWithChildren
  AppOnboardRoute: typeof AppOnboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppShellRouteRoute: AppShellRouteRouteWithChildren,
  AppOnboardRoute: AppOnboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
