/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppShellRouteRouteImport } from './routes/_app/_shell/route'
import { Route as AppOnboardRouteImport } from './routes/_app/onboard'
import { Route as AppShellAuthenticationRouteRouteImport } from './routes/_app/_shell/authentication/route'
import { Route as AppShellDashboardRouteImport } from './routes/_app/_shell/dashboard'
import { Route as AppShellFeaturesRouteRouteImport } from './routes/_app/_shell/features/route'
import { Route as AppShellLoginFlowsRouteImport } from './routes/_app/_shell/login-flows'
import { Route as AppShellSettingsRouteImport } from './routes/_app/_shell/settings'
import { Route as AppShellTestAccountsRouteImport } from './routes/_app/_shell/test-accounts'
import { Route as AppShellTestRunsRouteImport } from './routes/_app/_shell/test-runs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppShellAuthenticationIndexRouteImport } from './routes/_app/_shell/authentication/index'
import { Route as AppShellAuthenticationAccountsRouteImport } from './routes/_app/_shell/authentication/accounts'
import { Route as AppShellAuthenticationLoginFlowRouteImport } from './routes/_app/_shell/authentication/login-flow'
import { Route as AppShellFeaturesIndexRouteImport } from './routes/_app/_shell/features/index'
import { Route as AppShellFeaturesFeatureIdRouteImport } from './routes/_app/_shell/features/$featureId'
import { Route as ApiScreenshotsTestRunsTestRunIdStepIdRouteImport } from './routes/api/screenshots/test-runs/$testRunId/$stepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRouteRoute = AppShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShellAuthenticationRouteRoute =
  AppShellAuthenticationRouteRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AppShellRouteRoute,
  } as any)
const AppShellDashboardRoute = AppShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellFeaturesRouteRoute = AppShellFeaturesRouteRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellLoginFlowsRoute = AppShellLoginFlowsRouteImport.update({
  id: '/login-flows',
  path: '/login-flows',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellSettingsRoute = AppShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellTestAccountsRoute = AppShellTestAccountsRouteImport.update({
  id: '/test-accounts',
  path: '/test-accounts',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellTestRunsRoute = AppShellTestRunsRouteImport.update({
  id: '/test-runs',
  path: '/test-runs',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellAuthenticationIndexRoute =
  AppShellAuthenticationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppShellAuthenticationRouteRoute,
  } as any)
const AppShellAuthenticationAccountsRoute =
  AppShellAuthenticationAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AppShellAuthenticationRouteRoute,
  } as any)
const AppShellAuthenticationLoginFlowRoute =
  AppShellAuthenticationLoginFlowRouteImport.update({
    id: '/login-flow',
    path: '/login-flow',
    getParentRoute: () => AppShellAuthenticationRouteRoute,
  } as any)
const AppShellFeaturesIndexRoute = AppShellFeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellFeaturesRouteRoute,
} as any)
const AppShellFeaturesFeatureIdRoute =
  AppShellFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => AppShellFeaturesRouteRoute,
  } as any)
const ApiScreenshotsTestRunsTestRunIdStepIdRoute =
  ApiScreenshotsTestRunsTestRunIdStepIdRouteImport.update({
    id: '/api/screenshots/test-runs/$testRunId/$stepId',
    path: '/api/screenshots/test-runs/$testRunId/$stepId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboard': typeof AppOnboardRoute
  '/authentication': typeof AppShellAuthenticationRouteRouteWithChildren
  '/features': typeof AppShellFeaturesRouteRouteWithChildren
  '/dashboard': typeof AppShellDashboardRoute
  '/login-flows': typeof AppShellLoginFlowsRoute
  '/settings': typeof AppShellSettingsRoute
  '/test-accounts': typeof AppShellTestAccountsRoute
  '/test-runs': typeof AppShellTestRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authentication/accounts': typeof AppShellAuthenticationAccountsRoute
  '/authentication/login-flow': typeof AppShellAuthenticationLoginFlowRoute
  '/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/authentication/': typeof AppShellAuthenticationIndexRoute
  '/features/': typeof AppShellFeaturesIndexRoute
  '/api/screenshots/test-runs/$testRunId/$stepId': typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboard': typeof AppOnboardRoute
  '/dashboard': typeof AppShellDashboardRoute
  '/login-flows': typeof AppShellLoginFlowsRoute
  '/settings': typeof AppShellSettingsRoute
  '/test-accounts': typeof AppShellTestAccountsRoute
  '/test-runs': typeof AppShellTestRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authentication/accounts': typeof AppShellAuthenticationAccountsRoute
  '/authentication/login-flow': typeof AppShellAuthenticationLoginFlowRoute
  '/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/authentication': typeof AppShellAuthenticationIndexRoute
  '/features': typeof AppShellFeaturesIndexRoute
  '/api/screenshots/test-runs/$testRunId/$stepId': typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/_shell': typeof AppShellRouteRouteWithChildren
  '/_app/onboard': typeof AppOnboardRoute
  '/_app/_shell/authentication': typeof AppShellAuthenticationRouteRouteWithChildren
  '/_app/_shell/features': typeof AppShellFeaturesRouteRouteWithChildren
  '/_app/_shell/dashboard': typeof AppShellDashboardRoute
  '/_app/_shell/login-flows': typeof AppShellLoginFlowsRoute
  '/_app/_shell/settings': typeof AppShellSettingsRoute
  '/_app/_shell/test-accounts': typeof AppShellTestAccountsRoute
  '/_app/_shell/test-runs': typeof AppShellTestRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/_shell/authentication/accounts': typeof AppShellAuthenticationAccountsRoute
  '/_app/_shell/authentication/login-flow': typeof AppShellAuthenticationLoginFlowRoute
  '/_app/_shell/features/$featureId': typeof AppShellFeaturesFeatureIdRoute
  '/_app/_shell/authentication/': typeof AppShellAuthenticationIndexRoute
  '/_app/_shell/features/': typeof AppShellFeaturesIndexRoute
  '/api/screenshots/test-runs/$testRunId/$stepId': typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/onboard'
    | '/authentication'
    | '/features'
    | '/dashboard'
    | '/login-flows'
    | '/settings'
    | '/test-accounts'
    | '/test-runs'
    | '/api/auth/$'
    | '/authentication/accounts'
    | '/authentication/login-flow'
    | '/features/$featureId'
    | '/authentication/'
    | '/features/'
    | '/api/screenshots/test-runs/$testRunId/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/onboard'
    | '/dashboard'
    | '/login-flows'
    | '/settings'
    | '/test-accounts'
    | '/test-runs'
    | '/api/auth/$'
    | '/authentication/accounts'
    | '/authentication/login-flow'
    | '/features/$featureId'
    | '/authentication'
    | '/features'
    | '/api/screenshots/test-runs/$testRunId/$stepId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/_shell'
    | '/_app/onboard'
    | '/_app/_shell/authentication'
    | '/_app/_shell/features'
    | '/_app/_shell/dashboard'
    | '/_app/_shell/login-flows'
    | '/_app/_shell/settings'
    | '/_app/_shell/test-accounts'
    | '/_app/_shell/test-runs'
    | '/api/auth/$'
    | '/_app/_shell/authentication/accounts'
    | '/_app/_shell/authentication/login-flow'
    | '/_app/_shell/features/$featureId'
    | '/_app/_shell/authentication/'
    | '/_app/_shell/features/'
    | '/api/screenshots/test-runs/$testRunId/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiScreenshotsTestRunsTestRunIdStepIdRoute: typeof ApiScreenshotsTestRunsTestRunIdStepIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboard': {
      id: '/_app/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_shell/authentication': {
      id: '/_app/_shell/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AppShellAuthenticationRouteRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/dashboard': {
      id: '/_app/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppShellDashboardRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/features': {
      id: '/_app/_shell/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AppShellFeaturesRouteRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/login-flows': {
      id: '/_app/_shell/login-flows'
      path: '/login-flows'
      fullPath: '/login-flows'
      preLoaderRoute: typeof AppShellLoginFlowsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/settings': {
      id: '/_app/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppShellSettingsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/test-accounts': {
      id: '/_app/_shell/test-accounts'
      path: '/test-accounts'
      fullPath: '/test-accounts'
      preLoaderRoute: typeof AppShellTestAccountsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_app/_shell/test-runs': {
      id: '/_app/_shell/test-runs'
      path: '/test-runs'
      fullPath: '/test-runs'
      preLoaderRoute: typeof AppShellTestRunsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/authentication/': {
      id: '/_app/_shell/authentication/'
      path: '/'
      fullPath: '/authentication/'
      preLoaderRoute: typeof AppShellAuthenticationIndexRouteImport
      parentRoute: typeof AppShellAuthenticationRouteRoute
    }
    '/_app/_shell/authentication/accounts': {
      id: '/_app/_shell/authentication/accounts'
      path: '/accounts'
      fullPath: '/authentication/accounts'
      preLoaderRoute: typeof AppShellAuthenticationAccountsRouteImport
      parentRoute: typeof AppShellAuthenticationRouteRoute
    }
    '/_app/_shell/authentication/login-flow': {
      id: '/_app/_shell/authentication/login-flow'
      path: '/login-flow'
      fullPath: '/authentication/login-flow'
      preLoaderRoute: typeof AppShellAuthenticationLoginFlowRouteImport
      parentRoute: typeof AppShellAuthenticationRouteRoute
    }
    '/_app/_shell/features/': {
      id: '/_app/_shell/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof AppShellFeaturesIndexRouteImport
      parentRoute: typeof AppShellFeaturesRouteRoute
    }
    '/_app/_shell/features/$featureId': {
      id: '/_app/_shell/features/$featureId'
      path: '/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof AppShellFeaturesFeatureIdRouteImport
      parentRoute: typeof AppShellFeaturesRouteRoute
    }
    '/api/screenshots/test-runs/$testRunId/$stepId': {
      id: '/api/screenshots/test-runs/$testRunId/$stepId'
      path: '/api/screenshots/test-runs/$testRunId/$stepId'
      fullPath: '/api/screenshots/test-runs/$testRunId/$stepId'
      preLoaderRoute: typeof ApiScreenshotsTestRunsTestRunIdStepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppShellAuthenticationRouteRouteChildren {
  AppShellAuthenticationAccountsRoute: typeof AppShellAuthenticationAccountsRoute
  AppShellAuthenticationLoginFlowRoute: typeof AppShellAuthenticationLoginFlowRoute
  AppShellAuthenticationIndexRoute: typeof AppShellAuthenticationIndexRoute
}

const AppShellAuthenticationRouteRouteChildren: AppShellAuthenticationRouteRouteChildren =
  {
    AppShellAuthenticationAccountsRoute: AppShellAuthenticationAccountsRoute,
    AppShellAuthenticationLoginFlowRoute: AppShellAuthenticationLoginFlowRoute,
    AppShellAuthenticationIndexRoute: AppShellAuthenticationIndexRoute,
  }

const AppShellAuthenticationRouteRouteWithChildren =
  AppShellAuthenticationRouteRoute._addFileChildren(
    AppShellAuthenticationRouteRouteChildren,
  )

interface AppShellFeaturesRouteRouteChildren {
  AppShellFeaturesFeatureIdRoute: typeof AppShellFeaturesFeatureIdRoute
  AppShellFeaturesIndexRoute: typeof AppShellFeaturesIndexRoute
}

const AppShellFeaturesRouteRouteChildren: AppShellFeaturesRouteRouteChildren = {
  AppShellFeaturesFeatureIdRoute: AppShellFeaturesFeatureIdRoute,
  AppShellFeaturesIndexRoute: AppShellFeaturesIndexRoute,
}

const AppShellFeaturesRouteRouteWithChildren =
  AppShellFeaturesRouteRoute._addFileChildren(
    AppShellFeaturesRouteRouteChildren,
  )

interface AppShellRouteRouteChildren {
  AppShellAuthenticationRouteRoute: typeof AppShellAuthenticationRouteRouteWithChildren
  AppShellFeaturesRouteRoute: typeof AppShellFeaturesRouteRouteWithChildren
  AppShellDashboardRoute: typeof AppShellDashboardRoute
  AppShellLoginFlowsRoute: typeof AppShellLoginFlowsRoute
  AppShellSettingsRoute: typeof AppShellSettingsRoute
  AppShellTestAccountsRoute: typeof AppShellTestAccountsRoute
  AppShellTestRunsRoute: typeof AppShellTestRunsRoute
}

const AppShellRouteRouteChildren: AppShellRouteRouteChildren = {
  AppShellAuthenticationRouteRoute:
    AppShellAuthenticationRouteRouteWithChildren,
  AppShellFeaturesRouteRoute: AppShellFeaturesRouteRouteWithChildren,
  AppShellDashboardRoute: AppShellDashboardRoute,
  AppShellLoginFlowsRoute: AppShellLoginFlowsRoute,
  AppShellSettingsRoute: AppShellSettingsRoute,
  AppShellTestAccountsRoute: AppShellTestAccountsRoute,
  AppShellTestRunsRoute: AppShellTestRunsRoute,
}

const AppShellRouteRouteWithChildren = AppShellRouteRoute._addFileChildren(
  AppShellRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppShellRouteRoute: typeof AppShellRouteRouteWithChildren
  AppOnboardRoute: typeof AppOnboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppShellRouteRoute: AppShellRouteRouteWithChildren,
  AppOnboardRoute: AppOnboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiScreenshotsTestRunsTestRunIdStepIdRoute:
    ApiScreenshotsTestRunsTestRunIdStepIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
